<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	  <UserSecretsId>830d8705-7d8a-4c41-ad69-dc86ebab9e01</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
		<PackageReference Include="ClosedXML" Version="0.102.2" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0" />
		<PackageReference Include="Microsoft.ML" Version="3.0.1" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
		<PackageReference Include="SendGrid" Version="9.29.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\EquaMeridian.Core\EquaMeridian.Core.csproj" />
		<ProjectReference Include="..\EquaMeridian.Infrastructure\EquaMeridian.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Assets\equameridian-logo.jpg" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Assets\" />
	</ItemGroup>

</Project>