using EquaMeridian.DTOs.Reports;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Globalization;
using System.Security.Claims;
using System.Text;

/// <summary>
/// Reporting & Analytics gaps from the report: a dedicated revenue-summary endpoint (previously
/// only folded into the single dashboard aggregate), a transactional report with control breaks
/// (Category -> Month subtotals, Missing), adjustable criteria (date range + category filter),
/// exportable CSV/PDF, and machinery demand/usage-trend analytics (Missing). Admin-only, same
/// policy the dashboard and audit log already use.
///
/// PDF exports use PdfReportEngine — every PDF gets the EquaMeridian Holdings letterhead (logo +
/// wordmark), a "Generated by / at" stamp, KPI summary cards, real bar/line charts where the data
/// supports one, and a styled, paginated data table (not a plain text dump).
/// </summary>
[ApiController]
[Route("api/admin/reports")]
[Authorize(Policy = "AdminOnly")]
[ResponseCache(NoStore = true, Location = ResponseCacheLocation.None)]
public class AdminReportsController : ControllerBase
{
    private readonly IReportingRepository _repo;
    public AdminReportsController(IReportingRepository repo) => _repo = repo;

    /// <summary>Name of the currently signed-in admin, stamped into every exported report as
    /// "Generated by" — previously every export hardcoded a generic "EquaMeridian Admin Portal"
    /// string regardless of who actually ran it.</summary>
    private string GeneratedBy =>
        User.FindFirstValue(ClaimTypes.Name) ?? User.FindFirstValue(ClaimTypes.Email) ?? "EquaMeridian Admin Portal";

    [HttpGet("revenue-summary")]
    public async Task<IActionResult> GetRevenueSummary(
        [FromQuery] DateTime? from, [FromQuery] DateTime? to, [FromQuery] int? categoryId)
    {
        var report = await _repo.GetRevenueControlBreakReportAsync(from, to, categoryId);
        return Ok(report);
    }

    [HasPermission("Reports.Export")]
    [HttpGet("revenue-summary/export/csv")]
    public async Task<IActionResult> ExportRevenueCsv(
        [FromQuery] DateTime? from, [FromQuery] DateTime? to, [FromQuery] int? categoryId)
    {
        var report = await _repo.GetRevenueControlBreakReportAsync(from, to, categoryId);
        var bytes = Encoding.UTF8.GetBytes(BuildRevenueCsv(report));
        return File(bytes, "text/csv", $"revenue-summary-{AppTime.Now:yyyyMMdd-HHmmss}.csv");
    }

    [HasPermission("Reports.Export")]
    [HttpGet("revenue-summary/export/pdf")]
    public async Task<IActionResult> ExportRevenuePdf(
        [FromQuery] DateTime? from, [FromQuery] DateTime? to, [FromQuery] int? categoryId)
    {
        var report = await _repo.GetRevenueControlBreakReportAsync(from, to, categoryId);

        var doc = new PdfReportEngine("Revenue Summary", DateRangeSubtitle(report.From, report.To), GeneratedBy);

        doc.AddKpis(
            new PdfKpi("Grand Total", Money(report.GrandTotalAmount)),
            new PdfKpi("Transactions", report.GrandTransactionCount.ToString("N0", CultureInfo.InvariantCulture)),
            new PdfKpi("Platform Fees", Money(report.GrandPlatformFeeAmount)),
            new PdfKpi("Categories", report.Categories.Count.ToString(CultureInfo.InvariantCulture)));

        if (report.Categories.Count > 0 && report.GrandTotalAmount > 0)
        {
            var top = report.Categories.OrderByDescending(c => c.CategoryTotalAmount).First();
            var topShare = Pct(top.CategoryTotalAmount, report.GrandTotalAmount);
            var feeRate = Pct(report.GrandPlatformFeeAmount, report.GrandSubtotal);
            doc.AddInsight(
                "Key insight",
                $"{top.CategoryName} is the largest revenue category at {topShare} of platform total " +
                $"({Money(top.CategoryTotalAmount)} across {top.CategoryTransactionCount} transactions). " +
                $"Overall platform take-rate on subtotal is {feeRate}.");
        }

        // Monthly aggregate chart (all categories combined)
        var monthly = report.Categories
            .SelectMany(c => c.Months.Select(m => new { m.MonthLabel, m.Year, m.Month, m.TotalAmount, m.PlatformFeeAmount, m.TransactionCount }))
            .GroupBy(x => new { x.Year, x.Month, x.MonthLabel })
            .OrderBy(g => g.Key.Year).ThenBy(g => g.Key.Month)
            .Select(g => new {
                Label = ShortMonthLabel(g.Key.MonthLabel),
                Revenue = g.Sum(x => x.TotalAmount),
                Fees = g.Sum(x => x.PlatformFeeAmount)
            })
            .ToList();

        if (monthly.Count > 0)
        {
            doc.AddBarChart("Revenue by Month (all categories)",
                monthly.Select(m => m.Label).ToList(),
                new List<PdfChartSeries>
                {
                    new("Revenue (incl. fees)", monthly.Select(m => m.Revenue).ToList(), "D4A017"),
                    new("Platform Fees", monthly.Select(m => m.Fees).ToList(), "1A1A1A"),
                });
        }

        // Category ranking (horizontal) — clearer with long names
        var ranked = report.Categories.OrderByDescending(c => c.CategoryTotalAmount).Take(8).ToList();
        if (ranked.Count > 0)
        {
            doc.AddHorizontalBarChart(
                "Revenue by Category",
                ranked.Select(c => c.CategoryName).ToList(),
                ranked.Select(c => c.CategoryTotalAmount).ToList());
        }

        // Revenue share by category — mirrors the on-screen donut chart
        if (report.Categories.Count > 0)
        {
            doc.AddDonutChart("Revenue share by category", "Proportion of total revenue",
                report.Categories.Select(c => c.CategoryName).ToList(),
                report.Categories.Select(c => c.CategoryTotalAmount).ToList());
        }

        var rows = new List<PdfTableRow>();
        foreach (var category in report.Categories.OrderByDescending(c => c.CategoryTotalAmount))
        {
            rows.Add(new PdfTableRow(new[] { category.CategoryName, "", "", "", "", "" }, PdfRowStyle.GroupHeader));
            foreach (var month in category.Months)
            {
                rows.Add(new PdfTableRow(new[]
                {
                    "  " + month.MonthLabel,
                    month.TransactionCount.ToString(CultureInfo.InvariantCulture),
                    Money(month.Subtotal), Money(month.PlatformFeeAmount), Money(month.TotalAmount),
                    Pct(month.TotalAmount, report.GrandTotalAmount)
                }));
            }
            rows.Add(new PdfTableRow(new[]
            {
                "Category subtotal",
                category.CategoryTransactionCount.ToString(CultureInfo.InvariantCulture),
                Money(category.CategorySubtotal), Money(category.CategoryPlatformFeeAmount),
                Money(category.CategoryTotalAmount),
                Pct(category.CategoryTotalAmount, report.GrandTotalAmount)
            }, PdfRowStyle.Subtotal));
        }
        rows.Add(new PdfTableRow(new[]
        {
            "GRAND TOTAL",
            report.GrandTransactionCount.ToString(CultureInfo.InvariantCulture),
            Money(report.GrandSubtotal), Money(report.GrandPlatformFeeAmount), Money(report.GrandTotalAmount),
            "100%"
        }, PdfRowStyle.GrandTotal));

        doc.AddTable("Category Breakdown",
            new[] { "Category / Month", "Txns", "Subtotal", "Fees", "Total", "Share" },
            new[] { 155.0, 42.0, 90.0, 80.0, 90.0, 55.0 },
            new[] { false, true, true, true, true, true },
            rows,
            emptyMessage: "No invoiced revenue in this period.");

        doc.AddNote("Share is each row's contribution to the grand total. Cancelled invoices are excluded.");

        var bytes = doc.Build();
        return File(bytes, "application/pdf", $"revenue-summary-{AppTime.Now:yyyyMMdd-HHmmss}.pdf");
    }

        [HasPermission("Reports.Export")]
    [HttpGet("revenue-summary/export/xlsx")]
    public async Task<IActionResult> ExportRevenueXlsx(
        [FromQuery] DateTime? from, [FromQuery] DateTime? to, [FromQuery] int? categoryId)
    {
        var report = await _repo.GetRevenueControlBreakReportAsync(from, to, categoryId);
        var headers = new[] { "Category", "Month", "Transaction Count", "Subtotal", "Platform Fee", "Total Amount" };
        var rows = new List<IReadOnlyList<object?>>();

        foreach (var category in report.Categories)
        {
            foreach (var month in category.Months)
            {
                rows.Add(new object?[] { category.CategoryName, month.MonthLabel, month.TransactionCount,
                    month.Subtotal, month.PlatformFeeAmount, month.TotalAmount });
            }
            rows.Add(new object?[] { category.CategoryName, "SUBTOTAL", category.CategoryTransactionCount,
                category.CategorySubtotal, category.CategoryPlatformFeeAmount, category.CategoryTotalAmount });
        }
        rows.Add(new object?[] { "GRAND TOTAL", "", report.GrandTransactionCount,
            report.GrandSubtotal, report.GrandPlatformFeeAmount, report.GrandTotalAmount });

        var bytes = SimpleXlsxWriter.Generate(
            "Revenue Summary", headers, rows,
            reportTitle: "Revenue Summary (by Category, by Month)",
            generatedBy: GeneratedBy);
        return File(bytes, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            $"revenue-summary-{AppTime.Now:yyyyMMdd-HHmmss}.xlsx");
    }

    [HasPermission("Reports.Export")]
    [HttpGet("revenue-summary/export/docx")]
    public async Task<IActionResult> ExportRevenueDocx(
        [FromQuery] DateTime? from, [FromQuery] DateTime? to, [FromQuery] int? categoryId)
    {
        var report = await _repo.GetRevenueControlBreakReportAsync(from, to, categoryId);

        var doc = new DocxReportEngine("Revenue Summary", DateRangeSubtitle(report.From, report.To), GeneratedBy);

        doc.AddKpis(
            new DocxKpi("Grand Total", Money(report.GrandTotalAmount)),
            new DocxKpi("Transactions", report.GrandTransactionCount.ToString("N0", CultureInfo.InvariantCulture)),
            new DocxKpi("Platform Fees", Money(report.GrandPlatformFeeAmount)),
            new DocxKpi("Categories", report.Categories.Count.ToString(CultureInfo.InvariantCulture)));

        var docxRows = new List<DocxTableRow>();
        foreach (var category in report.Categories.OrderByDescending(c => c.CategoryTotalAmount))
        {
            docxRows.Add(new DocxTableRow(new[] { category.CategoryName, "", "", "", "", "" }, DocxRowStyle.GroupHeader));
            foreach (var month in category.Months)
            {
                docxRows.Add(new DocxTableRow(new[]
                {
                    "  " + month.MonthLabel,
                    month.TransactionCount.ToString(CultureInfo.InvariantCulture),
                    Money(month.Subtotal), Money(month.PlatformFeeAmount), Money(month.TotalAmount),
                    Pct(month.TotalAmount, report.GrandTotalAmount)
                }));
            }
            docxRows.Add(new DocxTableRow(new[]
            {
                "Category subtotal",
                category.CategoryTransactionCount.ToString(CultureInfo.InvariantCulture),
                Money(category.CategorySubtotal), Money(category.CategoryPlatformFeeAmount),
                Money(category.CategoryTotalAmount),
                Pct(category.CategoryTotalAmount, report.GrandTotalAmount)
            }, DocxRowStyle.Subtotal));
        }
        docxRows.Add(new DocxTableRow(new[]
        {
            "GRAND TOTAL",
            report.GrandTransactionCount.ToString(CultureInfo.InvariantCulture),
            Money(report.GrandSubtotal), Money(report.GrandPlatformFeeAmount), Money(report.GrandTotalAmount),
            "100%"
        }, DocxRowStyle.GrandTotal));

        doc.AddTable("Category Breakdown",
            new[] { "Category / Month", "Txns", "Subtotal", "Fees", "Total", "Share" },
            new[] { 2.6, 0.8, 1.4, 1.3, 1.4, 0.9 },
            new[] { false, true, true, true, true, true },
            docxRows,
            emptyMessage: "No invoiced revenue in this period.");

        doc.AddNote("Share is each row's contribution to the grand total. Cancelled invoices are excluded.");

        var bytes = doc.Build();
        return File(bytes, "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            $"revenue-summary-{AppTime.Now:yyyyMMdd-HHmmss}.docx");
    }

    [HttpGet("demand-trends")]
    public async Task<IActionResult> GetDemandTrends([FromQuery] DateTime? from, [FromQuery] DateTime? to)
    {
        var report = await _repo.GetDemandTrendReportAsync(from, to);
        return Ok(report);
    }

    [HasPermission("Reports.Export")]
    [HttpGet("demand-trends/export/csv")]
    public async Task<IActionResult> ExportDemandTrendsCsv([FromQuery] DateTime? from, [FromQuery] DateTime? to)
    {
        var report = await _repo.GetDemandTrendReportAsync(from, to);
        var bytes = Encoding.UTF8.GetBytes(BuildDemandCsv(report));
        return File(bytes, "text/csv", $"demand-trends-{AppTime.Now:yyyyMMdd-HHmmss}.csv");
    }

    [HasPermission("Reports.Export")]
    [HttpGet("demand-trends/export/pdf")]
    public async Task<IActionResult> ExportDemandTrendsPdf([FromQuery] DateTime? from, [FromQuery] DateTime? to)
    {
        var report = await _repo.GetDemandTrendReportAsync(from, to);

        int totalQuotes = report.Categories.Sum(c => c.QuotationRequestCount);
        int totalBookings = report.Categories.Sum(c => c.BookingCount);
        decimal overallConversion = totalQuotes > 0
            ? Math.Round((decimal)totalBookings / totalQuotes * 100m, 1)
            : 0;

        var doc = new PdfReportEngine("Machinery Demand & Usage Trends", DateRangeSubtitle(report.From, report.To), GeneratedBy);

        doc.AddKpis(
            new PdfKpi("Quotation Requests", totalQuotes.ToString("N0", CultureInfo.InvariantCulture)),
            new PdfKpi("Bookings", totalBookings.ToString("N0", CultureInfo.InvariantCulture)),
            new PdfKpi("Conversion Rate", overallConversion.ToString(CultureInfo.InvariantCulture) + "%"),
            new PdfKpi("Categories Tracked", report.Categories.Count.ToString(CultureInfo.InvariantCulture)));

        if (report.Categories.Count > 0)
        {
            var best = report.Categories.Where(c => c.QuotationRequestCount > 0)
                .OrderByDescending(c => c.ConversionRatePercent).FirstOrDefault();
            var busiest = report.Categories.OrderByDescending(c => c.QuotationRequestCount).First();
            var zeroConv = report.Categories.Count(c => c.QuotationRequestCount > 0 && c.BookingCount == 0);
            string insight =
                $"{busiest.CategoryName} attracted the most demand ({busiest.QuotationRequestCount} quote requests). ";
            if (best != null)
                insight += $"Best conversion: {best.CategoryName} at {best.ConversionRatePercent}%. ";
            if (zeroConv > 0)
                insight += $"{zeroConv} categor{(zeroConv == 1 ? "y has" : "ies have")} quotes with zero bookings — follow up opportunity.";
            doc.AddInsight("Demand snapshot", insight.Trim());
        }

        var topCategories = report.Categories.OrderByDescending(c => c.QuotationRequestCount).Take(10).ToList();
        if (topCategories.Count > 0)
        {
            doc.AddBarChart("Demand by Category",
                topCategories.Select(c => c.CategoryName).ToList(),
                new List<PdfChartSeries>
                {
                    new("Quotation Requests", topCategories.Select(c => (decimal)c.QuotationRequestCount).ToList(), "D4A017"),
                    new("Bookings", topCategories.Select(c => (decimal)c.BookingCount).ToList(), "1A1A1A"),
                },
                valuePrefix: "");
        }

        // Booking share by category — mirrors the on-screen donut chart
        if (topCategories.Count > 0)
        {
            doc.AddDonutChart("Booking share by category", "Where confirmed bookings come from",
                report.Categories.Select(c => c.CategoryName).ToList(),
                report.Categories.Select(c => (decimal)c.BookingCount).ToList(),
                valuePrefix: "");
        }

        if (report.MonthlyUsage.Count > 0)
        {
            doc.AddLineChart("Monthly Usage Trend",
                report.MonthlyUsage.Select(m => ShortMonthLabel(m.MonthLabel)).ToList(),
                new List<PdfChartSeries>
                {
                    new("Quotation Requests", report.MonthlyUsage.Select(m => (decimal)m.QuotationCount).ToList(), "D4A017"),
                    new("Bookings", report.MonthlyUsage.Select(m => (decimal)m.BookingCount).ToList(), "1A1A1A"),
                },
                valuePrefix: "");

            if (report.MonthlyUsage.Count >= 2)
            {
                var last = report.MonthlyUsage[^1];
                var prev = report.MonthlyUsage[^2];
                if (prev.QuotationCount > 0)
                {
                    var qChange = Math.Round((decimal)(last.QuotationCount - prev.QuotationCount) / prev.QuotationCount * 100m, 0);
                    var bChange = prev.BookingCount > 0
                        ? Math.Round((decimal)(last.BookingCount - prev.BookingCount) / prev.BookingCount * 100m, 0)
                        : 0;
                    doc.AddNote(
                        $"Latest month vs prior: quotations {(qChange >= 0 ? "+" : "")}{qChange}%, " +
                        $"bookings {(bChange >= 0 ? "+" : "")}{bChange}%.");
                }
            }
        }

        var rows = report.Categories
            .OrderByDescending(c => c.QuotationRequestCount)
            .Select(c => new PdfTableRow(new[]
            {
                c.CategoryName,
                c.QuotationRequestCount.ToString(CultureInfo.InvariantCulture),
                c.BookingCount.ToString(CultureInfo.InvariantCulture),
                c.ConversionRatePercent + "%",
                totalQuotes > 0 ? Pct(c.QuotationRequestCount, totalQuotes) : "0%"
            }))
            .ToList();

        doc.AddTable("Category Breakdown",
            new[] { "Category", "Quotes", "Bookings", "Conversion", "Demand Share" },
            new[] { 180.0, 70.0, 70.0, 80.0, 90.0 },
            new[] { false, true, true, true, true },
            rows,
            emptyMessage: "No quotation or booking activity in this period.");

        var bytes = doc.Build();
        return File(bytes, "application/pdf", $"demand-trends-{AppTime.Now:yyyyMMdd-HHmmss}.pdf");
    }

    [HasPermission("Reports.Export")]
    [HttpGet("demand-trends/export/xlsx")]
    public async Task<IActionResult> ExportDemandTrendsXlsx([FromQuery] DateTime? from, [FromQuery] DateTime? to)
    {
        var report = await _repo.GetDemandTrendReportAsync(from, to);
        var headers = new[] { "Category", "Quotation Requests", "Bookings", "Conversion Rate %" };
        var rows = report.Categories
            .Select(c => (IReadOnlyList<object?>)new object?[]
                { c.CategoryName, c.QuotationRequestCount, c.BookingCount, c.ConversionRatePercent })
            .ToList();

        var bytes = SimpleXlsxWriter.Generate(
            "Demand Trends", headers, rows,
            reportTitle: "Machinery Demand & Usage Trends",
            generatedBy: GeneratedBy);
        return File(bytes, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            $"demand-trends-{AppTime.Now:yyyyMMdd-HHmmss}.xlsx");
    }

    // ---- Simple list report: Active Listings (flat, no control breaks) ----

    [HttpGet("active-listings")]
    public async Task<IActionResult> GetActiveListings()
    {
        var report = await _repo.GetActiveListingsReportAsync();
        return Ok(report);
    }

    [HasPermission("Reports.Export")]
    [HttpGet("active-listings/export/csv")]
    public async Task<IActionResult> ExportActiveListingsCsv()
    {
        var report = await _repo.GetActiveListingsReportAsync();
        var sb = new StringBuilder();
        sb.AppendLine("Listing_ID,Title,Category,Supplier,Daily_Rate_ZAR,Location,Avg_Rating,Created_Date");
        foreach (var l in report.Listings)
        {
            sb.AppendLine(string.Join(",",
                l.ListingID.ToString(CultureInfo.InvariantCulture),
                CsvField(l.ListingTitle), CsvField(l.CategoryName), CsvField(l.SupplierName),
                l.DailyRateZAR.ToString(CultureInfo.InvariantCulture),
                CsvField(l.Location ?? ""), l.AverageRating.ToString(CultureInfo.InvariantCulture),
                l.CreatedDate.ToString("yyyy-MM-dd")));
        }
        var bytes = Encoding.UTF8.GetBytes(sb.ToString());
        return File(bytes, "text/csv", $"active-listings-{AppTime.Now:yyyyMMdd-HHmmss}.csv");
    }

    [HasPermission("Reports.Export")]
    [HttpGet("active-listings/export/pdf")]
    public async Task<IActionResult> ExportActiveListingsPdf()
    {
        var report = await _repo.GetActiveListingsReportAsync();

        var doc = new PdfReportEngine("Active Listings", "Current live marketplace inventory", GeneratedBy);

        decimal avgRate = report.Listings.Count > 0 ? report.Listings.Average(l => l.DailyRateZAR) : 0;
        var rated = report.Listings.Where(l => l.AverageRating > 0).ToList();
        decimal avgRating = rated.Count > 0 ? rated.Average(l => l.AverageRating) : 0;
        int categoryCount = report.Listings.Select(l => l.CategoryName).Distinct().Count();

        doc.AddKpis(
            new PdfKpi("Active Listings", report.TotalCount.ToString("N0", CultureInfo.InvariantCulture)),
            new PdfKpi("Avg. Daily Rate", Money(avgRate)),
            new PdfKpi("Avg. Rating", rated.Count > 0
                ? avgRating.ToString("N1", CultureInfo.InvariantCulture) + " / 5"
                : "No ratings yet"),
            new PdfKpi("Categories", categoryCount.ToString(CultureInfo.InvariantCulture)));

        // Complexity matrix: simple list reports export tables only (no charts).

        var rows = report.Listings
            .OrderBy(l => l.CategoryName).ThenByDescending(l => l.DailyRateZAR)
            .Select(l => new PdfTableRow(new[]
            {
                l.ListingTitle,
                l.CategoryName,
                l.SupplierName,
                Money(l.DailyRateZAR),
                string.IsNullOrWhiteSpace(l.Location) ? "—" : l.Location!,
                l.AverageRating > 0
                    ? l.AverageRating.ToString("N1", CultureInfo.InvariantCulture)
                    : "—"
            }))
            .ToList();

        doc.AddTable($"All Listings ({report.TotalCount})",
            new[] { "Title", "Category", "Supplier", "Daily Rate", "Location", "Rating" },
            new[] { 130.0, 80.0, 100.0, 75.0, 95.0, 50.0 },
            new[] { false, false, false, true, false, true },
            rows,
            emptyMessage: "No active listings on the marketplace.");

        doc.AddNote("Average rating excludes listings with no reviews. Only listings with status Active are included.");

        var bytes = doc.Build();
        return File(bytes, "application/pdf", $"active-listings-{AppTime.Now:yyyyMMdd-HHmmss}.pdf");
    }

    [HasPermission("Reports.Export")]
    [HttpGet("active-listings/export/xlsx")]
    public async Task<IActionResult> ExportActiveListingsXlsx()
    {
        var report = await _repo.GetActiveListingsReportAsync();
        var headers = new[] { "Listing ID", "Title", "Category", "Supplier", "Daily Rate (R)", "Location", "Avg Rating", "Created Date" };
        var rows = report.Listings
            .Select(l => (IReadOnlyList<object?>)new object?[]
            {
                l.ListingID, l.ListingTitle, l.CategoryName, l.SupplierName,
                l.DailyRateZAR, l.Location ?? "", l.AverageRating, l.CreatedDate
            })
            .ToList();

        var bytes = SimpleXlsxWriter.Generate(
            "Active Listings", headers, rows,
            reportTitle: "Active Listings Report",
            generatedBy: GeneratedBy);
        return File(bytes, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            $"active-listings-{AppTime.Now:yyyyMMdd-HHmmss}.xlsx");
    }

    // ---- Management report with a graph: monthly revenue/commission trend, rendered as an
    // actual bar chart (not a data table) ----

    [HttpGet("monthly-overview")]
    public async Task<IActionResult> GetMonthlyOverview([FromQuery] DateTime? from, [FromQuery] DateTime? to)
    {
        var report = await _repo.GetMonthlyOverviewReportAsync(from, to);
        return Ok(report);
    }

    [HasPermission("Reports.Export")]
    [HttpGet("monthly-overview/export/pdf")]
    public async Task<IActionResult> ExportMonthlyOverviewPdf([FromQuery] DateTime? from, [FromQuery] DateTime? to)
    {
        var report = await _repo.GetMonthlyOverviewReportAsync(from, to);
        var months = report.Months;
        var effectiveFrom = from ?? (months.Count > 0
            ? new DateTime(months[0].Year, months[0].Month, 1)
            : (DateTime?)null);

        var doc = new PdfReportEngine("Monthly Revenue & Commission Overview",
            DateRangeSubtitle(effectiveFrom, to), GeneratedBy);

        decimal totalRev = months.Sum(m => m.GrossRevenue);
        decimal totalComm = months.Sum(m => m.PlatformCommission);
        int totalBookings = months.Sum(m => m.BookingCount);

        doc.AddKpis(
            new PdfKpi("Total Bookings", totalBookings.ToString("N0", CultureInfo.InvariantCulture)),
            new PdfKpi("Total Revenue", Money(totalRev)),
            new PdfKpi("Total Commission", Money(totalComm)),
            new PdfKpi("Months Shown", months.Count.ToString(CultureInfo.InvariantCulture)));

        if (months.Count >= 1)
        {
            var peak = months.OrderByDescending(m => m.GrossRevenue).First();
            var takeRate = Pct(totalComm, totalRev);
            string insight =
                $"Peak month: {peak.MonthLabel} with {Money(peak.GrossRevenue)} gross " +
                $"({peak.BookingCount} bookings). Platform commission rate across the period: {takeRate}.";
            if (months.Count >= 2)
            {
                var last = months[^1];
                var prev = months[^2];
                if (prev.GrossRevenue > 0)
                {
                    var growth = Math.Round((last.GrossRevenue - prev.GrossRevenue) / prev.GrossRevenue * 100m, 1);
                    insight += $" Latest month vs prior: {(growth >= 0 ? "+" : "")}{growth}% revenue.";
                }
            }
            doc.AddInsight("Performance snapshot", insight);
        }

        if (months.Count > 0)
        {
            doc.AddBarChart("Gross Revenue vs. Platform Commission",
                months.Select(m => ShortMonthLabel(m.MonthLabel)).ToList(),
                new List<PdfChartSeries>
                {
                    new("Gross Revenue", months.Select(m => m.GrossRevenue).ToList(), "D4A017"),
                    new("Platform Commission", months.Select(m => m.PlatformCommission).ToList(), "1A1A1A"),
                });
        }

        var rows = months
            .Select(m => new PdfTableRow(new[]
            {
                m.MonthLabel,
                m.BookingCount.ToString(CultureInfo.InvariantCulture),
                Money(m.GrossRevenue),
                Money(m.PlatformCommission),
                Pct(m.GrossRevenue, totalRev),
                m.BookingCount > 0 ? Money(m.GrossRevenue / m.BookingCount) : "—"
            }))
            .ToList();

        if (months.Count > 0)
        {
            rows.Add(new PdfTableRow(new[]
            {
                "TOTAL",
                totalBookings.ToString(CultureInfo.InvariantCulture),
                Money(totalRev),
                Money(totalComm),
                "100%",
                totalBookings > 0 ? Money(totalRev / totalBookings) : "—"
            }, PdfRowStyle.GrandTotal));
        }

        doc.AddTable("Monthly Figures",
            new[] { "Month", "Bookings", "Gross Revenue", "Commission", "Share", "Avg / Booking" },
            new[] { 100.0, 65.0, 100.0, 90.0, 55.0, 90.0 },
            new[] { false, true, true, true, true, true },
            rows,
            emptyMessage: "No monthly revenue data for this period.");

        doc.AddNote("Gross revenue is invoice subtotal before platform fees. Commission is platform fee collected.");

        var bytes = doc.Build();
        return File(bytes, "application/pdf", $"monthly-overview-{AppTime.Now:yyyyMMdd-HHmmss}.pdf");
    }

    [HasPermission("Reports.Export")]
    [HttpGet("monthly-overview/export/xlsx")]
    public async Task<IActionResult> ExportMonthlyOverviewXlsx([FromQuery] DateTime? from, [FromQuery] DateTime? to)
    {
        var effectiveFrom = from ?? new DateTime(AppTime.Now.Year, AppTime.Now.Month, 1).AddMonths(-11);
        var report = await _repo.GetMonthlyOverviewReportAsync(effectiveFrom, to);
        var months = report.Months.TakeLast(12).ToList();

        var headers = new[] { "Month", "Bookings", "Gross Revenue (R)", "Platform Commission (R)" };
        var rows = months
            .Select(m => (IReadOnlyList<object?>)new object?[]
                { m.MonthLabel, m.BookingCount, m.GrossRevenue, m.PlatformCommission })
            .ToList();

        var bytes = SimpleXlsxWriter.GenerateWithBarChart(
            dataSheetName: "Monthly Overview",
            chartTitle: "Monthly Revenue & Commission",
            categoryLabels: months.Select(m => ShortMonthLabel(m.MonthLabel)).ToList(),
            seriesA: months.Select(m => m.GrossRevenue).ToList(),
            seriesAName: "Gross Revenue (R)",
            seriesB: months.Select(m => m.PlatformCommission).ToList(),
            seriesBName: "Platform Commission (R)",
            tableHeaders: headers,
            tableRows: rows,
            reportTitle: "Monthly Revenue & Commission Overview",
            generatedBy: GeneratedBy);

        return File(bytes, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            $"monthly-overview-{AppTime.Now:yyyyMMdd-HHmmss}.xlsx");
    }

    private static string ShortMonthLabel(string fullLabel)
    {
        var parts = fullLabel.Split(' ');
        return parts.Length == 2 ? $"{parts[0][..Math.Min(3, parts[0].Length)]} {parts[1][2..]}" : fullLabel;
    }

    // ---- Simple list report: Pending Supplier Approvals (flat, no control breaks) ----

    [HttpGet("pending-suppliers")]
    public async Task<IActionResult> GetPendingSuppliers()
    {
        var report = await _repo.GetPendingSupplierApprovalsReportAsync();
        return Ok(report);
    }

    [HasPermission("Reports.Export")]
    [HttpGet("pending-suppliers/export/csv")]
    public async Task<IActionResult> ExportPendingSuppliersCsv()
    {
        var report = await _repo.GetPendingSupplierApprovalsReportAsync();
        var sb = new StringBuilder();
        sb.AppendLine("User_ID,Full_Name,Email,Company_Name,Registration_Number,Applied_Date,Days_Pending");
        foreach (var s in report.Suppliers)
        {
            sb.AppendLine(string.Join(",",
                s.UserID.ToString(CultureInfo.InvariantCulture),
                CsvField(s.FullName), CsvField(s.Email), CsvField(s.CompanyName ?? ""),
                CsvField(s.RegistrationNumber ?? ""), s.CreatedDate.ToString("yyyy-MM-dd"),
                s.DaysPending.ToString(CultureInfo.InvariantCulture)));
        }
        var bytes = Encoding.UTF8.GetBytes(sb.ToString());
        return File(bytes, "text/csv", $"pending-suppliers-{AppTime.Now:yyyyMMdd-HHmmss}.csv");
    }

    [HasPermission("Reports.Export")]
    [HttpGet("pending-suppliers/export/pdf")]
    public async Task<IActionResult> ExportPendingSuppliersPdf()
    {
        var report = await _repo.GetPendingSupplierApprovalsReportAsync();

        var doc = new PdfReportEngine("Pending Supplier Approvals",
            "Suppliers awaiting admin review — prioritise by wait time", GeneratedBy);

        int oldestDays = report.Suppliers.Count > 0 ? report.Suppliers.Max(s => s.DaysPending) : 0;
        double avgDays = report.Suppliers.Count > 0 ? report.Suppliers.Average(s => s.DaysPending) : 0;
        int overdue7 = report.Suppliers.Count(s => s.DaysPending >= 7);
        int overdue14 = report.Suppliers.Count(s => s.DaysPending >= 14);

        doc.AddKpis(
            new PdfKpi("Awaiting Approval", report.TotalCount.ToString("N0", CultureInfo.InvariantCulture)),
            new PdfKpi("Oldest Pending", oldestDays + " days"),
            new PdfKpi("Average Wait", avgDays.ToString("N0", CultureInfo.InvariantCulture) + " days"),
            new PdfKpi("\u2265 7 Days", overdue7.ToString(CultureInfo.InvariantCulture)));

        if (report.Suppliers.Count > 0)
        {
            string insight =
                $"{report.TotalCount} supplier application{(report.TotalCount == 1 ? "" : "s")} waiting. ";
            if (overdue14 > 0)
                insight += $"{overdue14} have waited 14+ days and should be reviewed first. ";
            insight += $"Average queue time is {avgDays:0} days (oldest {oldestDays} days).";
            doc.AddInsight("Queue health", insight);
        }

        // Complexity matrix: simple list reports export tables only (no charts).

        var rows = report.Suppliers
            .OrderByDescending(s => s.DaysPending)
            .Select(s => new PdfTableRow(new[]
            {
                s.FullName,
                s.Email,
                s.CompanyName ?? "—",
                s.CreatedDate.ToString("d MMM yyyy", CultureInfo.InvariantCulture),
                s.DaysPending.ToString(CultureInfo.InvariantCulture),
                s.DaysPending >= 14 ? "Urgent" : s.DaysPending >= 7 ? "Due" : "Normal"
            }))
            .ToList();

        doc.AddTable($"Pending Suppliers ({report.TotalCount})",
            new[] { "Full Name", "Email", "Company", "Applied", "Days", "Priority" },
            new[] { 110.0, 140.0, 100.0, 78.0, 42.0, 55.0 },
            new[] { false, false, false, false, true, false },
            rows,
            emptyMessage: "No suppliers currently awaiting approval.");

        doc.AddNote("Priority: Urgent = 14+ days pending, Due = 7–13 days, Normal = under 7 days.");

        var bytes = doc.Build();
        return File(bytes, "application/pdf", $"pending-suppliers-{AppTime.Now:yyyyMMdd-HHmmss}.pdf");
    }

    [HasPermission("Reports.Export")]
    [HttpGet("pending-suppliers/export/xlsx")]
    public async Task<IActionResult> ExportPendingSuppliersXlsx()
    {
        var report = await _repo.GetPendingSupplierApprovalsReportAsync();
        var headers = new[] { "User ID", "Full Name", "Email", "Company Name", "Registration Number", "Applied Date", "Days Pending" };
        var rows = report.Suppliers
            .Select(s => (IReadOnlyList<object?>)new object?[]
            {
                s.UserID, s.FullName, s.Email, s.CompanyName ?? "",
                s.RegistrationNumber ?? "", s.CreatedDate, s.DaysPending
            })
            .ToList();

        var bytes = SimpleXlsxWriter.Generate(
            "Pending Suppliers", headers, rows,
            reportTitle: "Pending Supplier Approvals",
            generatedBy: GeneratedBy);
        return File(bytes, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            $"pending-suppliers-{AppTime.Now:yyyyMMdd-HHmmss}.xlsx");
    }

    // ---- Simple list report: Open Disputes (flat, no control breaks) ----

    [HttpGet("open-disputes")]
    public async Task<IActionResult> GetOpenDisputes()
    {
        var report = await _repo.GetOpenDisputesReportAsync();
        return Ok(report);
    }

    [HasPermission("Reports.Export")]
    [HttpGet("open-disputes/export/csv")]
    public async Task<IActionResult> ExportOpenDisputesCsv()
    {
        var report = await _repo.GetOpenDisputesReportAsync();
        var sb = new StringBuilder();
        sb.AppendLine("Dispute_ID,Booking_Reference,Contractor,Supplier,Reason_Category,Booking_Amount,Status,Raised_Date");
        foreach (var d in report.Disputes)
        {
            sb.AppendLine(string.Join(",",
                d.DisputeID.ToString(CultureInfo.InvariantCulture),
                CsvField(d.BookingReference), CsvField(d.ContractorName), CsvField(d.SupplierName),
                CsvField(d.ReasonCategory), d.BookingAmount.ToString(CultureInfo.InvariantCulture),
                CsvField(d.Status), d.RaisedDate.ToString("yyyy-MM-dd")));
        }
        var bytes = Encoding.UTF8.GetBytes(sb.ToString());
        return File(bytes, "text/csv", $"open-disputes-{AppTime.Now:yyyyMMdd-HHmmss}.csv");
    }

    [HasPermission("Reports.Export")]
    [HttpGet("open-disputes/export/pdf")]
    public async Task<IActionResult> ExportOpenDisputesPdf()
    {
        var report = await _repo.GetOpenDisputesReportAsync();

        var doc = new PdfReportEngine("Open Disputes",
            "Unresolved booking disputes — ordered by amount at risk", GeneratedBy);

        decimal totalAmount = report.Disputes.Sum(d => d.BookingAmount);
        double avgAge = report.Disputes.Count > 0
            ? report.Disputes.Average(d => (AppTime.Now.Date - d.RaisedDate.Date).TotalDays)
            : 0;

        doc.AddKpis(
            new PdfKpi("Open Disputes", report.TotalCount.ToString("N0", CultureInfo.InvariantCulture)),
            new PdfKpi("Amount at Risk", Money(totalAmount)),
            new PdfKpi("Avg. Age", avgAge.ToString("0", CultureInfo.InvariantCulture) + " days"),
            new PdfKpi("Statuses", report.Disputes.Select(d => d.Status).Distinct().Count()
                .ToString(CultureInfo.InvariantCulture)));

        if (report.Disputes.Count > 0)
        {
            var topReason = report.Disputes.GroupBy(d => d.ReasonCategory)
                .OrderByDescending(g => g.Count()).First();
            var largest = report.Disputes.OrderByDescending(d => d.BookingAmount).First();
            doc.AddInsight(
                "Risk snapshot",
                $"Most common reason: {topReason.Key} ({topReason.Count()} cases). " +
                $"Largest exposure: {Money(largest.BookingAmount)} on booking {largest.BookingReference} " +
                $"({largest.ContractorName} vs {largest.SupplierName}).");
        }

        // Complexity matrix: simple list reports export tables only (no charts).

        var rows = report.Disputes
            .OrderByDescending(d => d.BookingAmount)
            .Select(d => new PdfTableRow(new[]
            {
                d.BookingReference,
                d.ContractorName,
                d.SupplierName,
                d.ReasonCategory,
                Money(d.BookingAmount),
                d.Status,
                d.RaisedDate.ToString("d MMM yyyy", CultureInfo.InvariantCulture)
            }))
            .ToList();

        doc.AddTable($"Open Disputes ({report.TotalCount})",
            new[] { "Booking Ref", "Contractor", "Supplier", "Reason", "Amount", "Status", "Raised" },
            new[] { 78.0, 85.0, 85.0, 80.0, 75.0, 60.0, 70.0 },
            new[] { false, false, false, false, true, false, false },
            rows,
            emptyMessage: "No open disputes — all clear.");

        var bytes = doc.Build();
        return File(bytes, "application/pdf", $"open-disputes-{AppTime.Now:yyyyMMdd-HHmmss}.pdf");
    }

    [HasPermission("Reports.Export")]
    [HttpGet("open-disputes/export/xlsx")]
    public async Task<IActionResult> ExportOpenDisputesXlsx()
    {
        var report = await _repo.GetOpenDisputesReportAsync();
        var headers = new[] { "Dispute ID", "Booking Reference", "Contractor", "Supplier", "Reason Category", "Booking Amount (R)", "Status", "Raised Date" };
        var rows = report.Disputes
            .Select(d => (IReadOnlyList<object?>)new object?[]
            {
                d.DisputeID, d.BookingReference, d.ContractorName, d.SupplierName,
                d.ReasonCategory, d.BookingAmount, d.Status, d.RaisedDate
            })
            .ToList();

        var bytes = SimpleXlsxWriter.Generate(
            "Open Disputes", headers, rows,
            reportTitle: "Open Disputes Report",
            generatedBy: GeneratedBy);
        return File(bytes, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            $"open-disputes-{AppTime.Now:yyyyMMdd-HHmmss}.xlsx");
    }

    // ---- Transactional report #2: Supplier Performance (control-break: Supplier -> Month,
    // with subtotals + grand total) ----

    [HttpGet("supplier-performance")]
    public async Task<IActionResult> GetSupplierPerformance([FromQuery] DateTime? from, [FromQuery] DateTime? to)
    {
        var report = await _repo.GetSupplierPerformanceReportAsync(from, to);
        return Ok(report);
    }

    [HasPermission("Reports.Export")]
    [HttpGet("supplier-performance/export/csv")]
    public async Task<IActionResult> ExportSupplierPerformanceCsv([FromQuery] DateTime? from, [FromQuery] DateTime? to)
    {
        var report = await _repo.GetSupplierPerformanceReportAsync(from, to);
        var bytes = Encoding.UTF8.GetBytes(BuildSupplierPerformanceCsv(report));
        return File(bytes, "text/csv", $"supplier-performance-{AppTime.Now:yyyyMMdd-HHmmss}.csv");
    }

    [HasPermission("Reports.Export")]
    [HttpGet("supplier-performance/export/pdf")]
    public async Task<IActionResult> ExportSupplierPerformancePdf([FromQuery] DateTime? from, [FromQuery] DateTime? to)
    {
        var report = await _repo.GetSupplierPerformanceReportAsync(from, to);

        var doc = new PdfReportEngine("Supplier Performance", DateRangeSubtitle(report.From, report.To), GeneratedBy);

        doc.AddKpis(
            new PdfKpi("Grand Total", Money(report.GrandTotalAmount)),
            new PdfKpi("Transactions", report.GrandTransactionCount.ToString("N0", CultureInfo.InvariantCulture)),
            new PdfKpi("Platform Fees", Money(report.GrandPlatformFeeAmount)),
            new PdfKpi("Suppliers", report.Suppliers.Count.ToString(CultureInfo.InvariantCulture)));

        if (report.Suppliers.Count > 0 && report.GrandTotalAmount > 0)
        {
            var top = report.Suppliers.OrderByDescending(s => s.SupplierTotalAmount).First();
            var topShare = Pct(top.SupplierTotalAmount, report.GrandTotalAmount);
            var top3 = report.Suppliers.OrderByDescending(s => s.SupplierTotalAmount).Take(3).Sum(s => s.SupplierTotalAmount);
            doc.AddInsight(
                "Concentration",
                $"{top.SupplierName} leads with {topShare} of platform revenue " +
                $"({Money(top.SupplierTotalAmount)} across {top.SupplierTransactionCount} transactions). " +
                $"Top 3 suppliers account for {Pct(top3, report.GrandTotalAmount)} of total.");
        }

        // Use TotalAmount for ranking bars so chart matches table grand total
        var topSuppliers = report.Suppliers.OrderByDescending(s => s.SupplierTotalAmount).Take(10).ToList();
        if (topSuppliers.Count > 0)
        {
            doc.AddHorizontalBarChart(
                "Top suppliers by revenue",
                topSuppliers.Select(s => s.SupplierName).ToList(),
                topSuppliers.Select(s => s.SupplierTotalAmount).ToList());

            doc.AddBarChart("Revenue vs platform fees (top suppliers)",
                topSuppliers.Select(s => s.SupplierName.Length > 14 ? s.SupplierName[..12] + "…" : s.SupplierName).ToList(),
                new List<PdfChartSeries>
                {
                    new("Revenue", topSuppliers.Select(s => s.SupplierTotalAmount).ToList(), "D4A017"),
                    new("Platform Fees", topSuppliers.Select(s => s.SupplierPlatformFeeAmount).ToList(), "1A1A1A"),
                });
        }

        // Revenue concentration — mirrors the on-screen donut chart (top 5 suppliers vs the rest)
        if (report.Suppliers.Count > 0)
        {
            doc.AddDonutChart("Revenue concentration", "Top 5 suppliers vs the rest",
                report.Suppliers.Select(s => s.SupplierName).ToList(),
                report.Suppliers.Select(s => s.SupplierTotalAmount).ToList(),
                maxSlices: 6);
        }

        var rows = new List<PdfTableRow>();
        foreach (var supplier in report.Suppliers.OrderByDescending(s => s.SupplierTotalAmount))
        {
            rows.Add(new PdfTableRow(new[] { supplier.SupplierName, "", "", "", "", "" }, PdfRowStyle.GroupHeader));
            foreach (var month in supplier.Months)
            {
                rows.Add(new PdfTableRow(new[]
                {
                    "  " + month.MonthLabel,
                    month.TransactionCount.ToString(CultureInfo.InvariantCulture),
                    Money(month.Subtotal), Money(month.PlatformFeeAmount), Money(month.TotalAmount),
                    Pct(month.TotalAmount, report.GrandTotalAmount)
                }));
            }
            rows.Add(new PdfTableRow(new[]
            {
                "Supplier subtotal",
                supplier.SupplierTransactionCount.ToString(CultureInfo.InvariantCulture),
                Money(supplier.SupplierSubtotal), Money(supplier.SupplierPlatformFeeAmount),
                Money(supplier.SupplierTotalAmount),
                Pct(supplier.SupplierTotalAmount, report.GrandTotalAmount)
            }, PdfRowStyle.Subtotal));
        }
        rows.Add(new PdfTableRow(new[]
        {
            "GRAND TOTAL",
            report.GrandTransactionCount.ToString(CultureInfo.InvariantCulture),
            Money(report.GrandSubtotal), Money(report.GrandPlatformFeeAmount), Money(report.GrandTotalAmount),
            "100%"
        }, PdfRowStyle.GrandTotal));

        doc.AddTable("Supplier Breakdown",
            new[] { "Supplier / Month", "Txns", "Subtotal", "Fees", "Total", "Share" },
            new[] { 155.0, 42.0, 90.0, 80.0, 90.0, 55.0 },
            new[] { false, true, true, true, true, true },
            rows,
            emptyMessage: "No supplier revenue in this period.");

        doc.AddNote("Share is contribution to grand total revenue. Cancelled invoices excluded.");

        var bytes = doc.Build();
        return File(bytes, "application/pdf", $"supplier-performance-{AppTime.Now:yyyyMMdd-HHmmss}.pdf");
    }

    [HasPermission("Reports.Export")]
    [HttpGet("supplier-performance/export/xlsx")]
    public async Task<IActionResult> ExportSupplierPerformanceXlsx([FromQuery] DateTime? from, [FromQuery] DateTime? to)
    {
        var report = await _repo.GetSupplierPerformanceReportAsync(from, to);
        var headers = new[] { "Supplier", "Month", "Transaction Count", "Subtotal", "Platform Fee", "Total Amount" };
        var rows = new List<IReadOnlyList<object?>>();

        foreach (var supplier in report.Suppliers)
        {
            foreach (var month in supplier.Months)
            {
                rows.Add(new object?[]
                {
                    supplier.SupplierName, month.MonthLabel, month.TransactionCount,
                    month.Subtotal, month.PlatformFeeAmount, month.TotalAmount
                });
            }
            rows.Add(new object?[]
            {
                supplier.SupplierName, "SUBTOTAL", supplier.SupplierTransactionCount,
                supplier.SupplierSubtotal, supplier.SupplierPlatformFeeAmount, supplier.SupplierTotalAmount
            });
        }
        rows.Add(new object?[]
        {
            "GRAND TOTAL", "", report.GrandTransactionCount,
            report.GrandSubtotal, report.GrandPlatformFeeAmount, report.GrandTotalAmount
        });

        var bytes = SimpleXlsxWriter.Generate(
            "Supplier Performance", headers, rows,
            reportTitle: "Supplier Performance (by Supplier, by Month)",
            generatedBy: GeneratedBy);
        return File(bytes, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            $"supplier-performance-{AppTime.Now:yyyyMMdd-HHmmss}.xlsx");
    }

    // ---- Shared PDF formatting helpers ----

    private static string Money(decimal value) => "R" + value.ToString("N2", CultureInfo.InvariantCulture);

    private static string DateRangeSubtitle(DateTime? from, DateTime? to)
    {
        if (from == null && to == null)
            return "Full history \u2014 no date filter applied";
        string f = from?.ToString("d MMM yyyy", CultureInfo.InvariantCulture) ?? "Earliest record";
        string t = to?.ToString("d MMM yyyy", CultureInfo.InvariantCulture) ?? "Latest record";
        return $"Period: {f} \u2013 {t}";
    }

    private static string Pct(decimal part, decimal whole)
    {
        if (whole == 0) return "0%";
        return (part / whole * 100m).ToString("0.0", CultureInfo.InvariantCulture) + "%";
    }

    private static string BuildSupplierPerformanceCsv(SupplierPerformanceReportDto report)
    {
        var sb = new StringBuilder();
        sb.AppendLine("Supplier,Month,Transaction_Count,Subtotal,Platform_Fee,Total_Amount");

        foreach (var supplier in report.Suppliers)
        {
            foreach (var month in supplier.Months)
            {
                sb.AppendLine(string.Join(",",
                    CsvField(supplier.SupplierName),
                    CsvField(month.MonthLabel),
                    month.TransactionCount.ToString(CultureInfo.InvariantCulture),
                    month.Subtotal.ToString(CultureInfo.InvariantCulture),
                    month.PlatformFeeAmount.ToString(CultureInfo.InvariantCulture),
                    month.TotalAmount.ToString(CultureInfo.InvariantCulture)));
            }
            sb.AppendLine(string.Join(",",
                CsvField(supplier.SupplierName), "SUBTOTAL",
                supplier.SupplierTransactionCount.ToString(CultureInfo.InvariantCulture),
                supplier.SupplierSubtotal.ToString(CultureInfo.InvariantCulture),
                supplier.SupplierPlatformFeeAmount.ToString(CultureInfo.InvariantCulture),
                supplier.SupplierTotalAmount.ToString(CultureInfo.InvariantCulture)));
        }

        sb.AppendLine(string.Join(",", "GRAND TOTAL", "",
            report.GrandTransactionCount.ToString(CultureInfo.InvariantCulture),
            report.GrandSubtotal.ToString(CultureInfo.InvariantCulture),
            report.GrandPlatformFeeAmount.ToString(CultureInfo.InvariantCulture),
            report.GrandTotalAmount.ToString(CultureInfo.InvariantCulture)));

        return sb.ToString();
    }

    private static string BuildRevenueCsv(RevenueControlBreakReportDto report)
    {
        var sb = new StringBuilder();
        sb.AppendLine("Category,Month,Transaction_Count,Subtotal,Platform_Fee,Total_Amount");

        foreach (var category in report.Categories)
        {
            foreach (var month in category.Months)
            {
                sb.AppendLine(string.Join(",",
                    CsvField(category.CategoryName),
                    CsvField(month.MonthLabel),
                    month.TransactionCount.ToString(CultureInfo.InvariantCulture),
                    month.Subtotal.ToString(CultureInfo.InvariantCulture),
                    month.PlatformFeeAmount.ToString(CultureInfo.InvariantCulture),
                    month.TotalAmount.ToString(CultureInfo.InvariantCulture)));
            }
            sb.AppendLine(string.Join(",",
                CsvField(category.CategoryName), "SUBTOTAL",
                category.CategoryTransactionCount.ToString(CultureInfo.InvariantCulture),
                category.CategorySubtotal.ToString(CultureInfo.InvariantCulture),
                category.CategoryPlatformFeeAmount.ToString(CultureInfo.InvariantCulture),
                category.CategoryTotalAmount.ToString(CultureInfo.InvariantCulture)));
        }

        sb.AppendLine(string.Join(",", "GRAND TOTAL", "",
            report.GrandTransactionCount.ToString(CultureInfo.InvariantCulture),
            report.GrandSubtotal.ToString(CultureInfo.InvariantCulture),
            report.GrandPlatformFeeAmount.ToString(CultureInfo.InvariantCulture),
            report.GrandTotalAmount.ToString(CultureInfo.InvariantCulture)));

        return sb.ToString();
    }

    private static string BuildDemandCsv(DemandTrendReportDto report)
    {
        var sb = new StringBuilder();
        sb.AppendLine("Category,Quotation_Requests,Bookings,Conversion_Rate_Percent");
        foreach (var c in report.Categories)
        {
            sb.AppendLine(string.Join(",",
                CsvField(c.CategoryName),
                c.QuotationRequestCount.ToString(CultureInfo.InvariantCulture),
                c.BookingCount.ToString(CultureInfo.InvariantCulture),
                c.ConversionRatePercent.ToString(CultureInfo.InvariantCulture)));
        }
        sb.AppendLine();
        sb.AppendLine("Month,Quotation_Requests,Bookings");
        foreach (var m in report.MonthlyUsage)
        {
            sb.AppendLine(string.Join(",",
                CsvField(m.MonthLabel),
                m.QuotationCount.ToString(CultureInfo.InvariantCulture),
                m.BookingCount.ToString(CultureInfo.InvariantCulture)));
        }
        return sb.ToString();
    }

    private static string CsvField(string? value)
    {
        value ??= string.Empty;
        return value.Contains(',') || value.Contains('"') || value.Contains('\n')
            ? $"\"{value.Replace("\"", "\"\"")}\""
            : value;
    }
}